// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Odev.Models;

namespace Odev.Migrations
{
    [DbContext(typeof(TableContext))]
    [Migration("20211215141843_parselTableAdd")]
    partial class parselTableAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Odev.Models.Parsel", b =>
                {
                    b.Property<int>("ParselId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("PareselMahalle")
                        .HasColumnType("text");

                    b.Property<string>("ParselIl")
                        .HasColumnType("text");

                    b.Property<string>("ParselIlce")
                        .HasColumnType("text");

                    b.Property<string>("WktString")
                        .HasColumnType("text");

                    b.HasKey("ParselId");

                    b.ToTable("Parsels");
                });
#pragma warning restore 612, 618
        }
    }
}
